name: Accessibility Testing

on:
  workflow_run:
    workflows: ['pages-build-deployment']
    types:
      - completed

jobs:
  run-accessibility-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node environment
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install project dependencies
        run: npm ci

      - name: Install global dependencies
        run: npm install -g @unlighthouse/cli puppeteer

      - name: Run Tests
        run: unlighthouse-ci --config unlighthouse.config.ts --build-static --reporter jsonExpanded
